### ISSUE TITLE
Decide on output format of results

### ISSUE THREAD

**Issue by enygma** [psecio/parse#1]
Should the results be some kind of (*cringe*) XML output or a custom JSON format? XML might be easier to get the data into just because of all of the attributes and standard parting methods.

**Comment by hanneskod** [comment]
This could probably be closed as well? it seeme to have resolved organically.

Better to open new issues if the output model needs revision...

**Comment by redbeardcreator** [comment]
Yes, I think this can be closed. If we need JSON output (or whatever) in the future, thanks to you @hanneskod, I think we have it covered.
