### ISSUE TITLE
Add optional explanations to the test descriptions

### ISSUE THREAD

**Issue by redbeardcreator** [psecio/parse#11]
It would be nice to have explanations for the tests. For instance, I'm puzzling over why you should avoid `__DIR__` and `__FILE__`. An option to explain the whys would be great.

**Comment by hanneskod** [comment]
As hinted in #51 I would like to pick up on this. @redbeardcreator is on to something in the original comment, you could call it the educational aspect of this kind of tool.

I'm suggesting adding a `getLongDescription` method to `RuleInterface`.

A long description should explain why this particular rule is important, what could happen if the rule is ignored, include code examples that break the rule and information on how to resolve.

The long description could then be rendered using (`list-tests` was renamed `rules` in #51):

    psecio-parse rules name-of-rule

And after each reported issue we could add something like

    For more information execute 'psecio-parse rules name-of-rule'

The long decsription could also be renderd in xml/html (#5)  and so on..

This is of course super easy to implement, but writing good descriptions would require a joint effort..
