### ISSUE TITLE
Should the File argument to TestInterface::evaluate be removed?

### ISSUE THREAD

**Issue by hanneskod** [psecio/parse#27]
When looking at pr #26 we are now passing an empty mock of `File` when evaluating each test. This got my thinking, what is this `File` object really used for?

I see it being used in `TestUseTypeCheckEqualsOnBoolean` and `TestLogicalOperatorsFound`, both times to pull out a line of code and analyse it.

Of course, in php it is not necessary to put comparisons in one line. As it stands now I think `TestLogicalOperatorsFound` would fail when analysing something like

```php
if (
    $someCondition
    and $anotherCondition
) {
    // do something...
}
```

Would it be possible to rewrite `TestUseTypeCheckEqualsOnBoolean` and `TestLogicalOperatorsFound` so that no `File` object is used? And then remove this argument from `TestInterface::evaluate`? If so I think it would be an improvment.

**Comment by redbeardcreator** [comment]
If my preliminary tests last night are correct, `TestLogicalOperatorsFound` fails in many conditions. I expect to be looking at it in more detail over the next week or so.

I *think* (but am not sure and not in a position to check at the moment) that `PhpParser` provides some of the information needed to avoid parsing the line proper. But I think it is safe to parse the line, as you are examining the token itself, and that won't cross lines. It's just that the test doesn't account for all possible combinations.

**Comment by enygma** [comment]
I see lots of merges that reference this - can this issue be closed out now?

**Comment by hanneskod** [comment]
I think we should move to remove the `$file` argument from `evaluate`. I will submit a pr with this change. So maybe the disussion can continue there if you have objections.. So closing...

**Comment by hanneskod** [comment]
Or maybe it's better to leave it open and close from the pr instead..
