### ISSUE TITLE
What should the procedure be for accepting PRs?

### ISSUE THREAD

**Issue by redbeardcreator** [psecio/parse#41]
In #32 @hanneskod said:

> This is ready to merge. I am not sure how to do this. Maybe amongst the three of us we could say that two votes for and none against means it's ok to merge? As long as the suggested changes are not major anyways..

Below I say collaborator. I mean collaborator or owner.

My opinion is, if the code that will be run by the end user (that is, code in `src`) has minor and/or non-invasive and non-BC changes, it can be approved by a simple majority (2) of collaborators for now. If parse collects enough more collaborators, this would need to be revisited. This would include adding new tests and and adding more unit tests.

If you go much beyond this, especially if a change causes BC issues, I think everyone needs to at least chime in.

Something like documentation may only require a single collaborator's approval. Especially while the project matures.

I'd also suggest that a collaborator (in this case, not owner) needs approval from at least one other collaborator even for simpler changes, just as a safety check. This should be an overarching rule that always applies, with the possible exception of documentation.

Finally, until he decides otherwise, @enygma, as owner, gets veto power, and can do whatever he'd like.

**Comment by hanneskod** [comment]
Perfect.

**Comment by enygma** [comment]
I'm good with you guys making the call on the work you're doing. Just bring me in on the conversation if you feel like it might go against the intent of the project. I've been going through the different PRs as they come through but damn, you guys do a lot of work ;)

**Comment by hanneskod** [comment]
Yeah. It has been (and is) great fun working on this with you guys! Lots of great additions. Fast feedback. Good discussions and learning opportunities. Thank you both @enygma  and @redbeardcreator!

**Comment by redbeardcreator** [comment]
I'm certainly enjoying working on something new and outside my usual proprietary world. It's great seeing a project evolve so rapidly and well.

**Comment by enygma** [comment]
open source ftw! :)

**Comment by redbeardcreator** [comment]
Indeed...I've been wanting to find a project to contribute to. I just happened to see this via your PHP security site. And I've been so happy to contribute!

**Comment by hanneskod** [comment]
Closing this as the issue seems to be resolved :smile:
