### ISSUE TITLE
Activate travis

### ISSUE THREAD

**Issue by hanneskod** [psecio/parse#45]
With the latest additions parse longer finds issues in itself. Wich also means that the travis build now pass for the first time. So I'm thinking it's time to activate travis. I can't do it as it requires admin privileges. Could you do it @enygma? Or if you find it easier you cold grant me admin privileges temporarily and I can do it..

**Comment by enygma** [comment]
Done! :)

**Comment by hanneskod** [comment]
Cool! Closing..
