### ISSUE TITLE
Test name consistency

### ISSUE THREAD

**Issue by redbeardcreator** [psecio/parse#49]
As I continue my preliminary thinking on #10, I've been looking at test names. I've come to the realization that they are very inconsistent. Some start with `Avoid`, some start with `Use`, and both mean the same thing (avoid this; you're using this bad thing). Then some tests don't have a prefix at all. It seems @enygma named them organically (as would I).

I'd like to propose, before there's a code-level end-user reason to refer to the names, that we consider making the names more consistent. I know [naming things is hard](http://martinfowler.com/bliki/TwoHardThings.html), so I propose we come up with a naming convention. This is a (long) starting point. I may have it completely wrong, so feel free to critique and criticize. Or compliment if I got things right :smile: 

The part between the triangles (:small_red_triangle: :small_red_triangle_down:), or more likely an edited version, would go in developer documentation.

:small_red_triangle: 
## Naming tests
Test names should be consistent throughout the test suite. To help ensure this, we use a simple naming convention:

```
<what><optional-when>
```

That is, we name *what* the test is about and potentially add some modifiers saying *when* it should be tested..

An example of just a *what* would be `Eval`. Since `eval()` is (almost) always bad, we don't need to modify the test name. Another would be `BooleanEquality`, which enforces always using the identical operator (`===`) instead of the equals operator (`==`).  There's not much more involved in the concept so a modifier isn't needed.

An example of a *when* modifier is `EchoWithFileGetContents`. In general, using `echo` is safe and necessary. However, `echo file_get_contents()` is potentially a bad thing. There is potential for several tests to be about using `echo` with something dangerous; adding `WithFileGetContents` makes it clear what's being tested.
:small_red_triangle_down: 

### Notes
1. I intentionally omitted the `Test` prefix. More discussion below.
2. The examples are just that...there might be better ones to use. I'm also using the updated names I propose below.

## Discussion
I've found using `Test` as a prefix to be cumbersome. I really don't mind it in code (although `Tests\Eval` is also workable). But on the command line and in annotations, it will be quite cumbersome. These are all about tests, so specifying `Test` probably isn't necessary. So I'd personally like to see any UI not include the `Test` prefix. As a result,`--include-tests` and `--exclude-tests` would use the prefix-less version (or at least support it) and annotations would use the non-prefixed version. It's easy enough to add the prefix in code.

I think we're rapidly nearing the last reasonable time to rename the tests, so if it's going to happen, it needs to happen soonish.

### Updated test names
The following are my proposed name changes. I'm leaving `Test` out at this point as a convenience. I have not yet verified each one of these (although I did verify several), so some may be incorrect.

Old Name | New Name
---------|----------
AvoidGlobalsUse	              | GlobalsUse
AvoidHardcodedSensitiveValues | HardcodedSensitiveValues
AvoidRequestUse               | RequestUse
DisableDisplayErrors          | DisableDisplayErrors
EchoWithFileGetContents       | EchoWithFileGetContents
Eval                          | Eval
ExitOrDie                     | ExitOrDie, or just Exit
ExtractNotOverwrite           | Extract
HttpRawPostData               | HttpRawPostData
ImportRequestVariables        | ImportRequestVariables
LogicalOperatorsFound         | NamedLogicalOperators
NoEregFunctions               | EregFunctions
OutputWithVariable            | OutputWithVariable
SessionRegenFalse             | SessionRegen
SetHeaderWithInput            | SetHeaderWithInput
UseExecModifierInRegex        | RegexWithExecModifier
UseMysqlRealEscapeString      | MysqlRealEscapeString
UseParseStr                   | ParseStr
UseReadfile                   | Readfile
UseRunkitImport               | RunkitImport
UseSystemFunctions            | SystemFunctions
UseTypeCheckEqualsOnBoolean   | BooleanEquality

**Comment by hanneskod** [comment]
I have been thinking the same thing! The `<what><optional-when>` formula is very well found. Brilliant! Some of the test names could be even shorter:

* `DisableDisplayErrors` could be just `DisplayErrors`.
* `NamedLogicalOperators` could be `LogicalOperators`.
* And `BooleanEquality` shohuld maybe be `BooleanIdentity`.

I would also like to suggest calling these things `Rules` instead of `Tests`. It is of course of no technical importance, but it is somewhat confusing that we have tests (that is Psecio\Parse\Tests) and tests (phpunit test cases). If we are to rename everything this could be done at the same time. (Now or never I presume.)

That would mean we'd have classes like:

* `\Psecio\Parse\RuleInterface`
* `\Psecio\Parse\Rule\GlobalsUse`
* `\Psecio\Parse\Rule\HardcodedSensitiveValues`
* and so on...

**Comment by redbeardcreator** [comment]
I like your name suggestions. And I, too, have been struggling with `Tests` and unit tests. But I'm hesitant to change it. @enygma?

**Comment by enygma** [comment]
I'm all for changing this. When I was originally naming them, it was more of a readable kind of thing, not really a standard format. I think doing this is a great idea and I like the format proposed too - makes a lot more sense :)

**Comment by hanneskod** [comment]
Cool. Changing from `Test` to `Rule` obviously would mean touching a lot of files and a litte hassle. In the long run I think removing any kind of confusion is a good thing.

Have you started the work of renaming things already @redbeardcreator? If not I think I can submit a pr  tonight..

**Comment by redbeardcreator** [comment]
I hadn't started yet, no. But if you want to start on that I think I'm ready to start working on annotations tonight.

**Comment by hanneskod** [comment]
Perfect!
