### ISSUE TITLE
Maximum function nesting level of '100' reached

### ISSUE THREAD

**Issue by NoodlesNZ** [psecio/parse#58]
I'm trying to run parse against my codebase, but after a while it stops with this:

Fatal error: Maximum function nesting level of '100' reached, aborting! in /home/nick/testcomposer/vendor/psecio/parse/src/Psecio/Parse/TestCollection.php on line 45

It spits out a stack trace, but doesn't give any idea to what file it was working on when it had the problem. Is there any way to debug this?

**Comment by hanneskod** [comment]
Thanks for reporting!

Are you using the latest development version? Try using the `-vv` option to get verbose output. Please post the output you get when running:

    psecio-parse scan -vv dir

**Comment by NoodlesNZ** [comment]
I'm using 0.5.0 from composer (I guess, I'm new to composer). It seems the error occurs in a file where the same method is used 54 times. The php script itself isn't complex, we just use a method to swap out urls for images (between different CDNs), so `$site->cdn('/img/logo.gif')` and there just happens to be 54 images on this page.

**Comment by hanneskod** [comment]
Ok. You can specify `dev-master` instead of `0.5.0` in composer.json to get the develop version of parse. Would you mind posting the contents of the file in question? Or if it's an open source project direct me to it, so that I can try to recreate..

With `dev-master` it is also possible to scan individual files (it is not possible with 0.5). Try scanning just this file to see if the error remains..

**Comment by NoodlesNZ** [comment]
Same thing happens on dev-master (and when just scanning that one file). I can't post the code, so I'll try and recreate the problem.

**Comment by hanneskod** [comment]
ok, thanks! Would you mind posting the full stack trace?

**Comment by NoodlesNZ** [comment]
Here's a gist with the code: https://gist.github.com/NoodlesNZ/4bf0bca0ea0280f8acc5

**Comment by hanneskod** [comment]
Perfect! I will analyse and get back to you. Don't know exactly when, but I'll try to be quick. In the mean time you can skip this file when parsing using the `--ignore-paths` otion.

**Comment by NoodlesNZ** [comment]
Thanks :)

**Comment by hanneskod** [comment]
Ok I got it. This is related to xdebug. Setting `xdebug.max_nesting_level` to smething big, like 10 000 or so, solves the problem. Or turning xdebug off.

A fix will be merged into master some time soon. In the mean time you can edit your `php.ini` and everything should be fine..

**Comment by NoodlesNZ** [comment]
Thanks for looking into that and the fix.
