### ISSUE TITLE
Do not use the eval modifier in regular expressions (\e)

### ISSUE THREAD

**Issue by NoodlesNZ** [psecio/parse#60]
From what I can see, the script is looking for the existence of /e in a preg regex. This means that something like this gets incorrectly tagged as using the eval modifier:

`if (preg_match("#/enc/$#i", $_SERVER['REQUEST_URI'])) {`

You might need to do some work with determining which delimiters are being used (in this case # was used) to correctly identify the modifiers.

**Comment by hanneskod** [comment]
You are absolutely right. Good catch!

**Comment by hanneskod** [comment]
Hm. There are multiple problemens here. The `\e` modifier is only used with `preg_replace`.. A fix is in the loop...

**Comment by hanneskod** [comment]
Ok this is done. Thanks again for reporting @NoodlesNZ!
