### ISSUE TITLE
If variable name in conditional contains 'or' it evals as a logic operator problem

### ISSUE THREAD

**Issue by jminkler** [psecio/parse#64]
Avoid the use of logical operations (XOR, OR, etc) in favor of operators like && and ||
> if ( $email_order !== false ){

is example

**Comment by jminkler** [comment]
Guess is problem in PHPParse - closing

**Comment by hanneskod** [comment]
Thanks for reporting!

An older version of this test mistakenly scaned each line for the words `and` or `or`. If you use the latest development version of parse this problem should go away.

It would be great if you could verify that it does :smile: 

For reference se this pr: #36.

**Comment by jminkler** [comment]
Thanks, came up while I was using the security scanner that uses this lib.

**Comment by jminkler** [comment]
Thanks, missed that
