### ISSUE TITLE
Detect tainted input

### ISSUE THREAD

**Issue by marcaube** [psecio/parse#71]
Let's say I wanted add a rule (or rules) to detect when a variable is concatenated to a SQL query or a file path, and then trace back to see if the input was sanitized properly, how would I need to proceed?

I'd like to do a security analysis similar to what [Scrutinizer CI](https://scrutinizer-ci.com/tour/continuous-security-audits-for-your-application) does, but on-premise. Is it possible to do this statically with the PHP tokens?

**Comment by aik099** [comment]
If that SQL query is built purely from data present in a function (doesn't come from a function parameter values), then just concatenate values of corresponding tokens and you'll have final sql.

**Comment by marcaube** [comment]
Maybe my explanation wasn't clear (or I don't understand your answer).

The SQL query with concatenated variables is a *sink*, and I'm looking to trace back each variable to its *source* and check if they were sanitized or not along the way. If not, it's a tainted input and should be reported as a security vulnerability.

```
source -> ??? -> sink

source: $_GET, $_POST, $request->get(), etc.
sink: SQL
```

**Comment by aik099** [comment]
You can probably, but that would take too much effort to write such tool. Php parser would tell you what code is, but it's you who need to figure out what becomes what moves into what.

**Comment by enygma** [comment]
@marcaube Yeah, what you're talking about is flow analysis and is much more complex than this tool is designed to do. I've looked into building such a tool but it never evolved into something. I know the [RIPS](https://www.ripstech.com/) folks do that kind of analysis but theirs is a commercial product.

**Comment by marcaube** [comment]
Thanks for the answer @enygma, I'm closing the issue.
