### ISSUE TITLE
The "OutputWithVariable" rule false positive

### ISSUE THREAD

**Issue by aik099** [psecio/parse#74]
There are no variables in code, below, but `OutputWithVariable` rule thinks there is.

Code:

``` php
echo '<strong>Debug output above !!!</strong><br/>' . "\n";
```

Error:

```
Avoid the use of an output method (echo, print, etc) directly with a variable
```

**Comment by enygma** [comment]
Ah, I see - this is just checking "is it a string with something concatenated to it" not that the thing concatenated is a variable. I changed this in https://github.com/psecio/parse/commit/625c9916415f2e9487ef95097c0ba06bc91f0fb5 (and added a test). Thanks!
