### ISSUE TITLE
False positive for "ParseStr" rule

### ISSUE THREAD

**Issue by aik099** [psecio/parse#75]
The error says `Don't use 'mb_parse_str' or 'parse_str' as they sets variables into the current scope`, but that's not true, when `parse_str` was used with 2nd argument, that receives parsed values instead of extracting them into local scope:

```php
parse_str(html_entity_decode($url_components['query']), $url_params);
```

**Comment by jeroenherczeg** [comment]
+1 
`
Don't use 'mb_parse_str' or 'parse_str' as they sets variables into the current scope
>             parse_str($parts['query'], $query);
For more information execute 'psecio-parse rules ParseStr'
`

**Comment by enygma** [comment]
True, this rule should be updated to look for a second parameter. Anyone fancy a PR? :)

**Comment by aik099** [comment]
Here you go. It was easier to change existing rules, then I've expected at first. That's why I haven't sent PR back then.

**Comment by jeroenherczeg** [comment]
Thanks for fixing this!
