### ISSUE TITLE
Issue with using "String" class on PHP7

### ISSUE THREAD

**Issue by aik099** [psecio/parse#78]
On PHP7 there will be an error because of `String` class usage (~5 places in code). The `String_` class (already present in parser library) should be used instead.

**Comment by enygma** [comment]
Hey @aik099, can you try out the latest on `dev-master` and see if that resolves those issues for you?

**Comment by aik099** [comment]
I don't have any code at hand to test, but unit tests pass on PHP 7 and they have failed before. 

Turns out that library wasn't tested on PHP 7 and I've sent #80 PR that would do just that.

There is however another PR #76, which does a lot of stuff (like removing supported PHP versions, which I don't like) and locking to specific dependency version that work only on PHP 5.6+.
