### ISSUE TITLE
php fatal error (php7 related?)

### ISSUE THREAD

**Issue by lilmike** [psecio/parse#84]
When I run the command "psecio-parse scan ." I get:
Fatal error: Cannot use PhpParser\Node\Scalar\String as String because 'String' is a special class name in /home/lilmike/.config/composer/vendor/psecio/parse/src/Rule/Helper/IsFunctionCallTrait.php on line 9

I'm not sure what's going on, but the only thing I can think is perhaps php7 has messed something up, though I could easily be wrong.
-Michael.

**Comment by aik099** [comment]
The issue was fixed in https://github.com/psecio/parse/commit/d82cacb310deb9057b6891cefc8e587873922b18 commit. Not sure if a new version was released since then. Please use `dev-master` version of this library to get a fix.

**Comment by enygma** [comment]
Hi all, I just tagged the latest version of master with `2.10` to hopefully get this and other bugfixes into the latest release. Let me know if this doesn't work for you.

**Comment by danielnitscheladoo** [comment]
`0.7` 👎
`dev-master` 👍

**Comment by enygma** [comment]
Given that a release was made in response to this request, closing this out.
