### ISSUE TITLE
Parse php code before analysis. (Use Parser and other libraries) 

### ISSUE THREAD

**Issue by Rivendall** [psecio/parse#86]
Hello.
I research about analyzers. In them,  parser not be able to recognize include, require and etc expression. I want to know, how dose your program recognize path?
Did you use other library or tools? or did you develop this part in your app?

Thank you.

**Comment by aik099** [comment]
As per `composer.json` (see https://github.com/psecio/parse/blob/master/composer.json#L17) the `PHP-Parser` library is used to tokenize the code.

You need to recognize require/include statements for what purpose:

1. possible insecure usage
2. to compensate for missing autoloader

?

Just a guess, but security vulnerability is detected just by looking at given code fragment and not by analyzing class hierarchies.

**Comment by Rivendall** [comment]
Thank you for your answer. 
I think for true and accurate analysis, need to recognize all path and traverse them. 
For example in RIPS tool, without use of php parser and other library for create CFG and AST, can detect vulnerabilities in other path and complex path and nested classes. 
I want to know, how do tools detect them?

**Comment by aik099** [comment]
If source code of mentioned tools is available to you, then looking at it might give you a hint about how such things are checked.

Just a guess, but looking at rule specifics in this library they doesn't look like they're able to perform cross-file/class/method checks. For example this code might not be detected as vulnerable:

```php
function get_path() {
    return $_GET['path'];
}

require get_path();
```

**Comment by Rivendall** [comment]
RIPS detected vulnerability in your sample. (File Inclusion) 
But I want to know, one static code analyzer, recognize path in a project and traverse code for check vulnerabilities. 
For example in main code, there are some include and require file, then use in other class and there are vulnerabilities. 
I don't understand their mechanism.

**Comment by aik099** [comment]
You should worry about security vulnerabilities in code you own/can change. Don't worry about security vulnerabilities in code that you don't own/can't change.

For example if you're using 3rd party libraries through Composer and want to know if they're vulnerable or not use https://security.sensiolabs.org/check tool.

**Comment by Rivendall** [comment]
Thank you, but i want to know their mechanism until use in my app.
How to check tokens and traverse in one project with a lot of file and class?

**Comment by aik099** [comment]
Ah, you want to write your own tool using approaches taken by other tools. I see.

Then recommended approach remains the same:

* look at their source code
* ask authors/contributors of these libraries

As far as I can tell as contributor of this library it's:

1. tokenizing code using PHP-Parser
2. calls each rule for each tokenized node
3. rule then tells if it is the node it can process and if it's vulnerable code (see https://github.com/psecio/parse/blob/master/src/Rule/Extract.php)

Pretty simple.

I like this tool, because it's non-framework bound and can detect issues with all kinds of code.

**Comment by Rivendall** [comment]
Thank you so much. 
I have one question. why any free or commercial tools (for example WAP, RIPS, and etc) said in analysis, we have to create AST and then CFG and data flow analysis and etc? 
It is complex.

**Comment by aik099** [comment]
I have no idea.

From my expirience (I have built/used some tools that work with AST) you can't safely  `preg_match` over PHP file to detect stuff. Usually all `preg_match` rules fail when somebody formats analyzed code differently. This isn't the case with AST, where formatting isn't taken into account at all. It's always better to use tokenizers, that do create AST and then iterate over it.

**Comment by Rivendall** [comment]
Thank you for your answers. 
So, Should i use AST and this is enough?

**Comment by Rivendall** [comment]
Please see:
http://awap.sourceforge.net/support.html
http://rips-scanner.sourceforge.net/
https://websec.wordpress.com/category/projects/

**Comment by aik099** [comment]
> So, Should i use AST and this is enough?

That is what I recommend, yes.

**Comment by Rivendall** [comment]
Thank you, @aik099.

**Comment by aik099** [comment]
Unless you're a security expert yourself I recommend you hiring a security consultant that would do one time security audit over codebase, rather than reinventing a wheel and writing your own security vulnerability checking tool.

**Comment by Rivendall** [comment]
Thank you for your recommend. 
I want to become a security expert in this year. I can detect any vulnerabilities in php code with see code and audit them. but i need special tools to automate.

**Comment by aik099** [comment]
Wasn't aware of that. Good luck then.

**Comment by Rivendall** [comment]
You too. Thank you for your helps. they are useful.

**Comment by enygma** [comment]
Looks like this one was worked out - thanks @aik099! Closing.
