### ISSUE TITLE
Simplify composer requirements

### ISSUE THREAD

**Issue by garrettw** [psecio/parse#87]
In composer.json, the required packages have version constraints that looks like `"^1.0|^2.0"` or `"~2.5|~3.1"`. I think the number of options allowed by that could be what's making composer take several minutes to install this package. (It's installing as I type this, and I'm wondering how many more minutes it will take. It's already been more than 10.)
Could the older version numbers just be taken out?

**Comment by enygma** [comment]
@garrettw Thanks for the question - as it stands, though, the tool is written and requires certain versions of packages to ensure it works all the time. If the version numbers were removed (or the latest release was allowed) it could cause breakage in the tool as we wouldn't know what might have changed in the dependencies.

**Comment by garrettw** [comment]
I apologize if I wasn't clear. All I meant was, for example, changing `"^1.0|^2.0"` to `"^2.0"`.
The way it is now, I had to remove many other dependencies from my project that used later versions of the same packages just to get this one to the point where it wouldn't refuse to install. I could easily see that being a deterrent to adoption, as devs may try to install this, see that it's looking for older versions of the deps used by more common tools, and run away from this one thinking it's out of date and therefore of questionable usefulness.

**Comment by enygma** [comment]
Ah, okay - that makes more sense. I'm more than happy to accept a PR to simplify these if you'd like to submit!

**Comment by garrettw** [comment]
Sure, I'll do it. I might add that after a quick look at the [Network page](https://github.com/psecio/parse/network), I can see that multiple people have forked this just to update composer.json so they could use it alongside other packages. Might be good to keep this more up-to-date.

I may just go ahead and test it with newer versions of the deps as well.
